### PR TITLE
Replace use of 'colour' with 'color' and fix npm package.json

### PR DESCRIPTION
**Pull request by gpmcadam**
This pull request replaces the use of 'colour' with 'color' in options, but will actually accept either (to maintain support with previous versions.)

It also fixes some issues with grunt and npm to allow uglifying the code on all platforms.

Addresses issue #65 and allows more contributions.

### CODE REVIEW

**Comment by gpmcadam** [comment]
Also, the code had a mixture of tabs and spaces - I've included a commit here to make it more consistent using four spaces.

Y'know, because ...

**Comment by tommoor** [comment]
Wait, you're in the UK? Where's your sense of national pride man?

**Comment by gpmcadam** [comment]
Haha. I was tempted to stick a cheeky console warning in when the American alternative was used. 

[See also ...](https://www.addedbytes.com/blog/if-php-were-british/)

**Comment by tommoor** [comment]
Thanks for these, I reimplemented as part of a big weekend tidy :smile: 

https://github.com/tommoor/tinycon/commit/6a4e131cff0ba08ea863af34ce19cb9b1490468a

**Pull request closed without merging**
